[project]
name = "mcp-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=2.11.3",
    "markdownify>=1.2.0",
    "matplotlib>=3.10.6",
    "mcp[cli]>=1.13.1",
    "pydantic>=2.11.7",
    "sympy>=1.14.0",
]
